version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - DATABASE_NAME=search_pro
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres
  api:
    build: ./apps/api
    environment:
      - PORT=5000
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_TYPE=postgresql
      - DATABASE_SSL=false
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  db:
    driver: local
  pgadmin:
    driver: local
